const Act = {
    /** main */
    SET_MENU_OPENED: "SET_MENU_OPENED",
    SET_IS_FIREBASE_AUTH_ON: "SET_IS_FIREBASE_AUTH_ON",

    /** home */
    SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
    SET_PRE_SEARCH_VALUE: "SET_PRE_SEARCH_VALUE",
    //
    START_SEARCH: "START_SEARCH",
    PUSH_SEARCH_QUERY: "PUSH_SEARCH_QUERY",
    REMOVE_SEARCH_QUERY: "REMOVE_SEARCH_QUERY",
    CLEAR_SEARCH_CACHE: "CLEAR_SEARCH_CACHE",
    //
    SET_CUR_RESULT: "SET_CUR_RESULT",

    /** user */
};

export default Act;
